version: '3.9'

volumes:
  postgres_volume:
  mysql_volume:


services:

  dbpostgres:
    image: postgres
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 987654321
      POSTGRES_DB: BaseA

  dbmysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - mysql_volume:/var/lib/mysql
    ports:
    - "3306:3306"
    environment:
      MYSQL_USER: testuser
      MYSQL_USER_PASSWORD: 9876543211
      MYSQL_ROOT_PASSWORD: paS$w0rd
      MYSQL_DATABASE: BaseB
